allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(":app")
    
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            // Add all your dependency resolution logic here
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
