// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtHCA3pJy7XIliLwKlvwmYqS7fZ90L9UY',
    appId: '1:215921381040:web:e46f695af5e2e7fbfbf575',
    messagingSenderId: '215921381040',
    projectId: 'cinenook-flutter',
    authDomain: 'cinenook-flutter.firebaseapp.com',
    storageBucket: 'cinenook-flutter.firebasestorage.app',
    measurementId: 'G-LXV5GBNDME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByNYTjFSN2QuJ4mNWUe9H_v3gRN8unz1Y',
    appId: '1:215921381040:android:4b9eb3cb129ad214fbf575',
    messagingSenderId: '215921381040',
    projectId: 'cinenook-flutter',
    storageBucket: 'cinenook-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqkNbCePwaTQLBzO6v16ZhkI3mc5YEBtA',
    appId: '1:215921381040:ios:92b8bf20014d4279fbf575',
    messagingSenderId: '215921381040',
    projectId: 'cinenook-flutter',
    storageBucket: 'cinenook-flutter.firebasestorage.app',
    iosBundleId: 'io.flutter.app.cinenook',
  );
}
